### ISSUE TITLE
Line center points don't remove from SD Tracker

### ISSUE THREAD

**Issue by djgorman** [HaeffnerLab/Haeffner-Lab-LabRAD-Tools#25]
The remove points from the line center fit doesn't seem to work as expected. You can press remove line center but the points don't actually remove from either the graph or the fit until a new point is submitted.

**Comment by djgorman** [comment]
The issue seems to have to do with removing the all the points.

**Comment by urbaneg** [comment]
This is fixed with Boerge's latest updates to the drift tracker
