### ISSUE TITLE
Drift tracker settings

### ISSUE THREAD

**Issue by djgorman** [HaeffnerLab/Haeffner-Lab-LabRAD-Tools#35]
Drift tracker should be able to take line center and B field as options in addition to two lines.

**Comment by jayich** [comment]
I'm not too familiar here, but would a "Drift" class as input to Drift tracker that has B_field, line_center, and line_one, line_two as attributes help?

**Comment by bhemmerling** [comment]
Done. Tested at space time and seems to work.
