### ISSUE TITLE
Make all code compatible with latest pylabrad version

### ISSUE THREAD

**Issue by djgorman** [HaeffnerLab/Haeffner-Lab-LabRAD-Tools#8]
This could be a fair amount of work. But we should do it soon before we get too far behind.

**Comment by aransfor** [comment]
It is about a day of work, essentially just delete all the data.asarray() calls, the data is already an array now..

**Comment by djgorman** [comment]
Stuff seems to work. I'm gonna go ahead and mark this closed.
